// Sole generator/checker/copier for the committed setup runtime.
import { build, version as esbuildVersion } from 'esbuild';
import { createHash, randomBytes } from 'node:crypto';
import { isBuiltin } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const ARTIFACTS = [
  'setup-runtime.generated.mjs',
  'setup-runtime.generated.d.mts',
  'setup-runtime.LICENSE.txt',
];
const ENTRY = 'src/scripts/setup-runtime-entry.ts';
const SOURCE_INPUTS = new Set([
  ENTRY, 'src/scripts/database-setup.ts',
  'src/platform/commands.ts', 'src/platform/processes.ts',
]);
const PACKAGES = new Set(['cross-spawn', 'isexe', 'path-key', 'shebang-command', 'shebang-regex', 'which']);
const slash = value => value.split(path.sep).join('/');
const readJson = file => JSON.parse(fs.readFileSync(file, 'utf8'));
const digest = bytes => createHash('sha256').update(bytes).digest('hex');

function packageOwner(root, input) {
  let directory = path.dirname(path.resolve(root, input));
  const floor = path.join(root, 'node_modules');
  while (directory.startsWith(floor + path.sep)) {
    if (fs.existsSync(path.join(directory, 'package.json'))) return directory;
    directory = path.dirname(directory);
  }
  throw new Error(`No dependency owner for ${input}`);
}

export async function renderRuntime(root = ROOT) {
  const pkg = readJson(path.join(root, 'package.json'));
  const lock = readJson(path.join(root, 'package-lock.json'));
  if (pkg.devDependencies?.esbuild !== '0.28.2' || esbuildVersion !== '0.28.2'
      || lock.packages?.['node_modules/esbuild']?.version !== esbuildVersion) {
    throw new Error('setup runtime requires pinned esbuild 0.28.2');
  }
  if (pkg.dependencies?.['cross-spawn'] !== '7.0.6') throw new Error('cross-spawn pin drift');
  const result = await build({
    absWorkingDir: root, entryPoints: [ENTRY], outfile: 'setup-runtime.generated.mjs',
    bundle: true, platform: 'node', target: 'node24', format: 'esm',
    write: false, metafile: true, sourcemap: false, charset: 'utf8',
    legalComments: 'inline', logLevel: 'silent',
    banner: { js: "// GENERATED by scripts/setup-runtime.mjs --write; do not edit.\nimport { createRequire as setupCreateRequire } from 'node:module';\nconst require = setupCreateRequire(import.meta.url);" },
  });
  if (result.warnings.length || result.outputFiles.length !== 1) throw new Error('ambiguous bootstrap output');
  for (const output of Object.values(result.metafile.outputs)) {
    for (const edge of output.imports) {
      if (!edge.external || !isBuiltin(edge.path)) throw new Error(`Bootstrap external dependency: ${edge.path}`);
    }
  }
  const owners = new Map();
  for (const input of Object.keys(result.metafile.inputs)) {
    const relative = slash(path.relative(root, path.resolve(root, input)));
    if (relative.startsWith('../') || path.isAbsolute(relative)) throw new Error('Bootstrap input escapes checkout');
    if (!relative.startsWith('node_modules/')) {
      if (!SOURCE_INPUTS.has(relative)) throw new Error(`Unreviewed bootstrap source: ${relative}`);
      continue;
    }
    const directory = packageOwner(root, input);
    const dep = readJson(path.join(directory, 'package.json'));
    const key = slash(path.relative(root, directory));
    if (!PACKAGES.has(dep.name) || !['MIT', 'ISC'].includes(dep.license)
        || lock.packages?.[key]?.version !== dep.version) throw new Error(`Unreviewed dependency: ${key}`);
    owners.set(key, { directory, dep });
  }
  if (owners.size !== PACKAGES.size
      || new Set([...owners.values()].map(owner => owner.dep.name)).size !== PACKAGES.size) {
    throw new Error('Bootstrap dependency census changed');
  }
  const notices = [];
  for (const key of [...owners.keys()].sort()) {
    const { directory, dep } = owners.get(key);
    const licenses = fs.readdirSync(directory).filter(name => /^licen[cs]e(?:\.(?:txt|md))?$/i.test(name));
    if (licenses.length !== 1) throw new Error(`Cannot select license for ${key}`);
    const license = fs.readFileSync(path.join(directory, licenses[0]), 'utf8').replace(/\r\n/g, '\n').trimEnd();
    if (!license) throw new Error(`Empty license for ${key}`);
    notices.push(`${dep.name}@${dep.version} (${dep.license})\n${license}\n`);
  }
  // Entry contains only Task3's three export-from declarations. The declaration
  // facade refers to canonical TS definitions rather than duplicating signatures.
  const declarations = fs.readFileSync(path.join(root, ENTRY), 'utf8').replace(/\r\n/g, '\n');
  return new Map([
    [ARTIFACTS[0], result.outputFiles[0].text],
    [ARTIFACTS[1], declarations],
    [ARTIFACTS[2], 'Bundled setup dependencies — license notices\n\n' + notices.join('\n')],
  ]);
}

function requireCurrent(root, outputs) {
  for (const [name, expected] of outputs) {
    const file = path.join(root, 'src', 'scripts', name);
    if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== expected) {
      throw new Error(`Stale setup runtime: ${name}; run npm run build:setup-runtime and review the diff`);
    }
  }
}

function writeAtomic(directory, name, text) {
  const temporary = path.join(directory, `.${name}.${randomBytes(8).toString('hex')}.tmp`);
  try {
    fs.writeFileSync(temporary, text, { flag: 'wx', mode: 0o644 });
    fs.renameSync(temporary, path.join(directory, name));
  } finally {
    fs.rmSync(temporary, { force: true });
  }
}

export async function runRuntime(mode, root = ROOT) {
  if (!['--write', '--check', '--copy'].includes(mode)) throw new Error('usage: setup-runtime.mjs --write|--check|--copy');
  const outputs = await renderRuntime(root);
  if (mode !== '--write') requireCurrent(root, outputs);
  if (mode === '--write' || mode === '--copy') {
    const directory = path.join(root, mode === '--write' ? 'src' : 'build', 'scripts');
    if (!fs.statSync(directory).isDirectory()) throw new Error(`Missing output directory: ${directory}`);
    // Runtime JS is one atomic file, not an atomic three-file transaction.
    // An incomplete declaration/license set fails check/build and is retryable.
    for (const [name, text] of outputs) writeAtomic(directory, name, text);
  }
  return Object.fromEntries([...outputs].map(([name, text]) => [name, digest(text)]));
}

if (process.argv[1] && fs.realpathSync(fileURLToPath(import.meta.url)) === fs.realpathSync(path.resolve(process.argv[1]))) {
  try {
    if (process.argv.length !== 3) throw new Error('usage: setup-runtime.mjs --write|--check|--copy');
    await runRuntime(process.argv[2]);
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
